trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- bash: yarn run build
  displayName: Build extension

- bash: yarn run test-only
  displayName: Run Tests

- bash: yarn run vscode:package
  displayName: Package vscode extension

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: vscode-extension
    PathtoPublish: artifacts/extension/
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: vscode-extension-package
    PathtoPublish: artifacts/package/