trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
pool:
  vmImage: $(imageName)
steps:
- template: install-node-and-dependencies.yml
- script: yarn run build
  displayName: Build extension
- bash: yarn run test-only
  displayName: Run Tests
- bash: yarn run vscode:package-only
  displayName: Package vscode extension
- publish: artifacts/extension
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  artifact: vscode-extension
- publish: artifacts/package
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  artifact: vscode-extension-package